#INCLUDE THIS ONCE

'for reference - don't need to include

MACRO LibErrA = 151 'invalid arg
MACRO LibErrB = 152 'out of bounds
MACRO LibErrC = 153 'null callback
MACRO LibErrF = 154 'file operation failed
MACRO LibErrH = 155 'null or invalid handle
MACRO LibErrI = 156 'not implemented
MACRO LibErrL = 157 'locking error
MACRO LibErrM = 158 'memory allocation failed
MACRO LibErrN = 159 'invalid null value
MACRO LibErrP = 160 'null or invalid ptr
MACRO LibErrO = 161 'null or invalid object
MACRO LibErrR = 162 'required initialization value not set
MACRO LibErrS = 163 'null or invalid str
MACRO LibErrU = 164 'unexpected results
